server:
  port: 8088

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/shopapp?useSSL=false&serverTimezone=UTC
    username: root
    password: 12345678
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

api:
  prefix: api/v1

jwt:
  expiration: 2592000
  secretKey: P9LYvSWkmp/ncf0Uewt+EUUrAltRZPDRpJROqgwXn/0=









